version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ALCHEMY_DATABASE_URL=postgresql://postgres:postgres@db:5432/go_game
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: uvicorn go_game.server:app --host 0.0.0.0 --port 8080 --reload

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: 