"""Add draw offer columns to Game model

Revision ID: 413237fcac5d
Revises: c1e0bb7d58da
Create Date: 2025-03-10 10:46:42.437875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413237fcac5d'
down_revision = 'c1e0bb7d58da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('draw_offered_by_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('draw_offered_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['draw_offered_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'draw_offered_at')
    op.drop_column('games', 'draw_offered_by_id')
    # ### end Alembic commands ###
