"""add game timing and move history fields

Revision ID: c1e0bb7d58da
Revises: 
Create Date: 2025-02-20 10:18:56.971981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e0bb7d58da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('last_move_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('move_count', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('black_time_remaining', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('white_time_remaining', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('black_last_move_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('white_last_move_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'white_last_move_at')
    op.drop_column('games', 'black_last_move_at')
    op.drop_column('games', 'white_time_remaining')
    op.drop_column('games', 'black_time_remaining')
    op.drop_column('games', 'move_count')
    op.drop_column('games', 'last_move_at')
    op.drop_column('games', 'created_at')
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
